		--CONFIGURACION DE NOMBRE LOGICOS

/*
	SEMANA 05
*/

--Creando la BD
CREATE DATABASE SEMANA_05_BD
GO

--Activamos la BD
USE SEMANA_05_BD
GO

--Creamos la tabla categoria con sus restricciones fuera de la tabla
CREATE TABLE CATEGORIA
(
	IDCATEGORIA INT NOT NULL IDENTITY(1,1),
	CATEGORIA VARCHAR(60)NOT NULL,
	DESCRIPCION VARCHAR(100),
	HABILITADO BIT DEFAULT 1
)

--Configurar las restricciones modificando la tabla
ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA_IDCATEGORIA PRIMARY KEY(IDCATEGORIA)
GO

ALTER TABLE CATEGORIA ADD CONSTRAINT U_CATEGORIA_CATEGORIA UNIQUE(CATEGORIA)
GO

--Creamos la tabla producto con sus restricciones fuera de la tabla
CREATE TABLE PRODUCTO
(
	IDPRODUCTO INT IDENTITY(1,1) NOT NULL,
	PRODUCTO VARCHAR(100)NOT NULL,
	IDCATEGORIA INT NOT NULL,
	STOCK INT NOT NULL,
	PRECIO_UNIT DECIMAL(10,2)NOT NULL,
	PORC_OFERTA DECIMAL(5,2)NOT NULL,
	HABILITADO BIT DEFAULT 1
)
GO

--Configurar las restricciones modificando la tabla
ALTER TABLE PRODUCTO ADD CONSTRAINT PK_PRODUCTO_IDPRODUCTO PRIMARY KEY(IDPRODUCTO)
GO

ALTER TABLE PRODUCTO ADD CONSTRAINT U_PRODUCTO_PRODUCTO UNIQUE(PRODUCTO)
GO

ALTER TABLE PRODUCTO ADD CONSTRAINT CK_PRODUCTO_STOCK CHECK(STOCK>=0)
GO

ALTER TABLE PRODUCTO ADD CONSTRAINT CK_PRODUCTO_PRECIO_UNIT CHECK(PRECIO_UNIT >= 0)
GO

ALTER TABLE PRODUCTO ADD CONSTRAINT CK_PRODUCTO_PORC_OFERTA CHECK(PORC_OFERTA >= 0 AND PORC_OFERTA <= 20)
GO

ALTER TABLE PRODUCTO ADD CONSTRAINT DF_PRODUCTO_PRECIO_UNIT DEFAULT 0 FOR PRECIO_UNIT
GO

ALTER TABLE PRODUCTO ADD CONSTRAINT DF_PRODUCTO_STOCK DEFAULT 0 FOR STOCK
GO

ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PRODUCTO_IDCATEGORIA FOREIGN KEY(IDCATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)

--VERIFICAMOS LAS PROPIEDADES DE UNA TABLA

SP_HELP CATEGORIA
GO

--Insertamos datos en categoria
INSERT INTO CATEGORIA(CATEGORIA,DESCRIPCION) VALUES ('BEBIDAS','BEBIDAS INSDUSTRIALIZADAS CON ALTO INDICE DE AZUCAR')

--Visuañizamos los datos de la tabla categoria
SELECT * FROM CATEGORIA

INSERT INTO CATEGORIA(CATEGORIA,DESCRIPCION) VALUES ('LACTEOS','PRODUCTOS DERIBADOS DE LA LECHE')

SP_HELP PRODUCTO


--Insertando las restricciones dentro de la tabla
CREATE TABLE VENDEDOR
(
	IDVENDEDOR CHAR(8) NOT NULL,
	NOMBRE_VEN VARCHAR(100)NOT NULL,
	APELLIDOS_VEN VARCHAR(100)NOT NULL,
	SUELDO DECIMAL(10,2)NOT NULL,
	TELEFONO VARCHAR(15)NOT NULL,
	FECHA_INGRESO DATE DEFAULT GETDATE(),
	DISPONIBLE BIT DEFAULT 1,
	CONSTRAINT PK_VENDEDOR_IDVENDEDOR PRIMARY KEY(IDVENDEDOR),
	CONSTRAINT CK_VENDEDOR_SUELDO CHECK(SUELDO >=1130 AND SUELDO <= 5000),
	CONSTRAINT U_VENDEDOR_TELEFONO UNIQUE(TELEFONO)
)
GO

--Creamos la tabla VENTA
CREATE TABLE VENTA
(
	NROVENTA INT IDENTITY(1,1)NOT NULL,
	FECHA_HORA DATETIME DEFAULT GETDATE(),
	IDVENDEDOR CHAR(8)NOT NULL,
	TOTAL DECIMAL(10,2) DEFAULT 0,
	CONSTRAINT PK_VENTA_NROVENTA PRIMARY KEY(NROVENTA),
	CONSTRAINT FK_VENTA_IDVENDEDOR FOREIGN KEY(IDVENDEDOR) REFERENCES VENDEDOR(IDVENDEDOR)
)
GO

--Creamos la tabla DETALLE
CREATE TABLE DETALLE
(
	NROVENTA INT NOT NULL,
	IDPRODUCTO INT NOT NULL,
	CANTIDAD INT NOT NULL,
	PRECIO_COMP DECIMAL(10,2)NOT NULL,
	CONSTRAINT PK_DETALLE_NROVENTA_IDPRODUCTO PRIMARY KEY(NROVENTA,IDPRODUCTO),
	CONSTRAINT FK_DETALLE_NROVENTA FOREIGN KEY(NROVENTA) REFERENCES VENTA(NROVENTA),
	CONSTRAINT FK_DETALLE_IDPRODUCTO FOREIGN KEY(IDPRODUCTO) REFERENCES PRODUCTO(IDPRODUCTO)
)