/*
			CREAR - MODIFICAR - ELIMINAR
			tablas en una BD 
*/

--creamos la BD
CREATE DATABASE BD_SEMANA_03
GO --sirve para indicar a que comando va direccionar

--Activamos la DB
USE BD_SEMANA_03
GO

/*
	CREAMOS UNA TABLA
	=================

	Al ser un objeto de la BD usaremos el LDD (lenguaje de definicion de datos)
	SINTAXIS:
	CREATE TABLE Nombre_Tabla
	(
		Columna1 Tipo_Dato [NULL/NOT NULL],
		.
		.
		.
		ColumnaN Tipo_Dato [NULL/NOT NULL]
	)
*/

CREATE TABLE ALUMNO
(
	DNI CHAR(8) NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	APELLIDO VARCHAR(100) NOT NULL,
	CODIGO VARCHAR(7) NOT NULL,
	CARRERA VARCHAR(30) NOT NULL,
	FECHA_NAC DATE,
	--TELEFONO VARCHAR(15) NOT NULL
)
GO


--MODIFICAMOS LA TABLA AGREGANDO UNA NUEVA COLUMNA
ALTER TABLE ALUMNO ADD TELEFONO VARCHAR (15) --OJO si la BD tiene contenido, no pongas NOT NULL
GO

--MODIFICAMOS UNA TABLA PERO LE CAMBIAMOS EL TIPO DE DATO A UNA COLUMNA
ALTER TABLE ALUMNO ALTER COLUMN FECHA_NAC DATETIME
GO

--MODIFICAMOS LA PROPIEDAD DE UNA COLUMNA NULL A NOT NULL
ALTER TABLE ALUMNO ALTER COLUMN TELEFONO VARCHAR(15) NOT NULL
GO

--ELIMINAMOS UNA COLUMNA DE LA TABLA
ALTER TABLE ALUMNO DROP COLUMN CARRERA
GO
